### ISSUE TITLE
Strata 0.7.0 crashes

### ISSUE THREAD

**Issue by MDiTullio85** [arkottke/strata#15]
Dear Albert,
Strata 0.7.0 crashes when the maximum shear strain profile is required as output.
I don't know why but in files attached to the software there aren't problem.
I uploaded my file.

[RSL.zip](https://github.com/arkottke/strata/files/4332945/RSL.zip)

Best regards,
M

**Comment by arkottke** [comment]
@MDiTullio85 I believe I have fixed your issue. Can you test [this version](https://ci.appveyor.com/api/buildjobs/o7xvv5l8g9fc3rll/artifacts/build%2FStrata-x86-v0.7.0-092bfb8.zip) fix your issue?

**Comment by MDiTullio85** [comment]
Dear Albert,
now everything works fine.
King regards,
M
