### ISSUE TITLE
G/Gmax and Damping Iteration in Equivalent Linear Method

### ISSUE THREAD

**Issue by tianyey** [arkottke/strata#18]
Dear developers,

I ran the test problem (Shake2000b example problem) provided in the strata v0.8.0 zip file, and exported profile-damping, profile-shear modulus, profile-max strain files. when I compare the Strata G/Gmax and damping values for each layer vs. the interpolated G/Gmax and damping values using (effective strain ratio times strain at mid-depth of each layer), the results did not match. When I interpolate G/Gmax and damping values, I use linear interpolation of log10(strain) vs. G/Gmax or damping.

Please see below screenshot. The maximum error for G/Gmax is 2% at layer 3 (depth = 15 ft) and the maximum error for damping is 5.7% also at layer 3 (depth = 15 ft). These errors become large when I run problems with larger strains. I wonder if I'm using the correct method to interpret G/Gmax and damping from effective strain (max strain at mid depth of each layer times effective strain ratio). 

I also doublechecked that the auto-discretization is off.

![Capture](https://user-images.githubusercontent.com/30670024/132029969-55b008bc-7eec-4ad9-9074-d4fecb363fcb.JPG)

I appreciate your help in advance.
Andrew

**Comment by arkottke** [comment]
This is fixed with cb4946a
