### ISSUE TITLE
very high error

### ISSUE THREAD

**Issue by FedeTadd89** [arkottke/strata#20]
Good morning, I’m an italian geologist. I’m am currently using your Strata software to obtain response spenctrums at surface. I’m having some issues when I compute datas I’ve set in the software: the problem is the percentage of error which is very high and not acceptable for my project.
Here you can see the stats:
Method: equivalent linear
Maximum n° iterations: 60
Error tolerance: 2%

Starting Strata Calculation
7 Trial(s) (1 Site(s) and 7 Motion(s) )
[1 of 1] Generating site and soil properties
[1 of 7] Computing site response for motion: WAVEFORMS_SET_1\E.SRC0.00.HNN.D.IT-1976-0027.ACC.MP.ASC
!! -- Maximum number of iterations reached (60). Maximum Error: 64.45 %
[2 of 7] Computing site response for motion: WAVEFORMS_SET_1\IT.0LAI.00.HGN.D.IT-2012-0061.ACC.MP.ASC
!! -- Maximum number of iterations reached (60). Maximum Error: 45.52 %
[3 of 7] Computing site response for motion: WAVEFORMS_SET_1\IT.MNF.00.HGN.D.EMSC-20160824_0000006.ACC.MP.ASC
!! -- Maximum number of iterations reached (60). Maximum Error: 186.33 %
[4 of 7] Computing site response for motion: WAVEFORMS_SET_1\IV.MDAR..HNE.D.EMSC-20160824_0000006.ACC.MP.ASC
!! -- Maximum number of iterations reached (60). Maximum Error: 109.54 %
[5 of 7] Computing site response for motion: WAVEFORMS_SET_1\IV.T1218..HNE.D.EMSC-20161026_0000095.ACC.MP.ASC
!! -- Maximum number of iterations reached (60). Maximum Error: 129.14 %
[6 of 7] Computing site response for motion: WAVEFORMS_SET_1\IV.TERO..HNE.D.EMSC-20160824_0000006.ACC.MP.ASC
!! -- Maximum number of iterations reached (60). Maximum Error: 138.07 %
[7 of 7] Computing site response for motion: WAVEFORMS_SET_1\KO.DEMR..HNE.D.EMSC-20151006_0000093.ACC.MP.ASC
!! -- Maximum number of iterations reached (60). Maximum Error: 92.00 %
Computing statistics.

My question is: how can I reduce the error to zero?
Thank you

**Comment by arkottke** [comment]
Please provide your input file or screenshots of the motions, nonlinear
curves, and soil profile.

**Comment by FedeTadd89** [comment]
![argille damping](https://user-images.githubusercontent.com/115151128/194346979-04ea30d3-8962-4235-b2e1-157b4afd124a.JPG)
![argille ggmax](https://user-images.githubusercontent.com/115151128/194347008-7c66e0b7-a5b6-4243-8334-86325b4aeb76.JPG)
![Cattura](https://user-images.githubusercontent.com/115151128/194347010-802fba86-809a-41cd-9158-f5253c544245.JPG)
![limi Belforte damping](https://user-images.githubusercontent.com/115151128/194347012-c35f7d06-c076-4329-a1a7-84416fef7c31.JPG)
![limi Belforte ggmax](https://user-images.githubusercontent.com/115151128/194347015-57a5a3b4-d46b-47a9-82e1-057343055fed.JPG)
![sabbie cementate damping](https://user-images.githubusercontent.com/115151128/194347017-9517b97e-bb16-46cc-a214-a5fe45ad7b44.JPG)
![sabbie cementate ggmax](https://user-images.githubusercontent.com/115151128/194347019-a82163dc-44dd-4d39-ad6c-b64207bd0dd7.JPG)
![soil profile](https://user-images.githubusercontent.com/115151128/194347022-b1b722bf-b1bf-498b-9780-e5eddd8fa002.JPG)
![input](https://user-images.githubusercontent.com/115151128/194347458-94938797-4f65-4251-92cf-dec24da2a21c.JPG)

**Comment by FedeTadd89** [comment]
please tell me if you need more

**Comment by FedeTadd89** [comment]
1st pic: Argille damping
2nd pic: argille G/Gmax
3rd pic: soil type
4th pic: limo sabbioso damping
5th pic: limo sabbioso G/Gmax
6th pic: sabbie cementate damping
7th pic: sabbie cementate G/Gmax
8th pic: soil profile
9th pic: input motions

**Comment by arkottke** [comment]
Your first nonlinear curve has a G/Gmax value of 0 at 0 strain. Remove this
value as it probably causes issues with the interpolation.

**Comment by FedeTadd89** [comment]
that was the problem, now I don'have any error during computing process. Thank you so much!!!

**Comment by arkottke** [comment]
Glad it was easy to resolve.
