### ISSUE TITLE
Transfer function in Version 399 vs Version 426

### ISSUE THREAD

**Issue by bhavesh-bhanda** [arkottke/strata#3]
Dear Albert,
With reference to your mail, please find attached screenshots of inputs and output using version 399 and 426.
The problem is in output **Ratio - 0.00m (Outcrop 2A) from 10.00m (Outcrop 2A) -Acceleration TF.** hence the screenshot of that output is only. I was using Ver 399 and when I got this output it was obvious that this is wrong hence I checked for STRATA manual to check how thi TF is calculated to confirm. Also I modelled the same thin in SHAKE2000. Results of SHAKE 2000 and Ver 426 matches well. 
The Soil Type Rock has G/Gmax and Damping function from Schnabel, 1973 similar to SHAKE2000.

There are some changes in other TFs also but for transfer function like above are significant where second layer is also assigned as Outcrop.
I could have sent you the STRATA files but this system is not allowing the same.

![tr_ver_399](https://cloud.githubusercontent.com/assets/24908711/21632705/cee50b62-d26e-11e6-8e5d-cadee8320f84.jpg)
![1](https://cloud.githubusercontent.com/assets/24908711/21632708/cee95956-d26e-11e6-8343-f796a2f2a700.jpg)
![2](https://cloud.githubusercontent.com/assets/24908711/21632706/cee6f21a-d26e-11e6-9ab7-f0c57d0c2d8d.jpg)
![3](https://cloud.githubusercontent.com/assets/24908711/21632709/cee9d566-d26e-11e6-8fad-7471088c7026.jpg)
![4](https://cloud.githubusercontent.com/assets/24908711/21632707/cee94df8-d26e-11e6-8914-ecac505cd287.jpg)
![5](https://cloud.githubusercontent.com/assets/24908711/21632710/ceeae546-d26e-11e6-8707-f1d4273d9b41.jpg)
![tr_ver_426](https://cloud.githubusercontent.com/assets/24908711/21632711/cf162fe4-d26e-11e6-8522-8da3c45ebf7a.jpg)

**Comment by arkottke** [comment]
Thanks for this question. Can you post the profile for the earlier revision? Alternatively, you could host the revision 399 input file on something like Dropbox and share the link.

**Comment by bhavesh-bhanda** [comment]
Thanks for the prompt reply. The profile for the earlier version is same. Actually its the same file which I created using previous version. When I unlocked and ran it using new version I got different results. 
The link to the locked files is https://www.dropbox.com/sh/vzbktmvcuslea8y/AAC_vnvf9KMziNsd6lI3R2yxa?dl=0
Results of newer version looks correct and they are also matching with results of SHAKE2000.

**Comment by arkottke** [comment]
I see the problem, but I don't understand the cause of the difference. I will look into it and get back to you.

**Comment by arkottke** [comment]
The change in behavior is a result of a bug within the location lookup function that relates a provided depth to a layer and depth within that layer. The change was relatively minor from less than to less than or equal to:

**Revision 399:**
```cpp
        while (index <= m_subLayers.size()
                && m_subLayers.at(index).depthToBase() < depth)
            ++index;
```
**Current:**
```cpp
        while (index <= m_subLayers.size()
                && m_subLayers.at(index).depthToBase() <= depth)
            ++index;
```

However, for some profiles this minor change can be significant. In your example, the revision 399 code computed the transfer function as the ratio between the surface and 10 m within the first layer (left). In the current revision, the transfer function is computed as the ratio between the surface and the top of the second layer (right). You can see the changes in either code by computing the transfer function at using depths of 9.99 m and 10.01 m in the profile that you provided.

![transfer_functions](https://cloud.githubusercontent.com/assets/1033651/21654016/a3827d34-d268-11e6-8ff8-f8d05c9c8a30.png)

**Comment by bhavesh-bhanda** [comment]
Thanks for the reply.
This was really a major change in my view as the previous version will always give wrong result for a single layer problem. Also, as already incorporated in second version, transfer function mus be calculated between surface to top of the layer otherwise the won't be able to account for the impedance contrast and will show de-amplification due to damping.
Thanks again.
