### ISSUE TITLE
v0.5.5 - Within motion

### ISSUE THREAD

**Issue by vipulkmm** [arkottke/strata#7]
Unable to specify the location of input motion other than at Bedrock. On selecting the 'Specify depth' window, there is no additional window to specify the input depth based on soil layering.

**Comment by arkottke** [comment]
@vipulkmm The widget is a combo box that can be used to provide a depth (replaces "Specify a depth...").

![image](https://user-images.githubusercontent.com/1033651/45655610-05cd4700-ba96-11e8-89c1-2554f57f9bf7.png)
