### ISSUE TITLE
Crashes when using multiple ground motions and acceleration transfer function output 

### ISSUE THREAD

**Issue by julianovt** [arkottke/strata#9]
Strata will crash just after calculation begins when computing acceleration transfer function for 800 motions. Spectral Ratio computes fine, but when acceleration transfer function is added to desired outputs, Strata will crash before computing first motion. Also checked Fourier amplitude spectrum and has trouble computing it as well, which makes sense since transfer function won't compute. Any thought?

**Comment by julianovt** [comment]
There appears to be a bug in RVT when calculating transfer functions, since I was able to compute transfer functions with time series

**Comment by arkottke** [comment]
Thanks for this information. I will look into this issue.

**Comment by arkottke** [comment]
@julianovt Does this version still cause issues for you? 

https://github.com/arkottke/strata/releases/tag/v0.6.0-beta

**Comment by julianovt** [comment]
@arkottke That version isn't causing crashes anymore. Also appears to have been an issue with my input motion suite

**Comment by arkottke** [comment]
I am glad to hear that it is resolved.
